/**
 * Phase 2: The Lantern PDF - Professional Portability
 *
 * Generates a clean, formal "Logistical Ledger" that the user can share with:
 * - Funeral directors
 * - Airlines (for human remains transport)
 * - Banks and financial institutions
 *
 * The document removes the burden of explaining everything repeatedly.
 * It's a distilled, professional summary of what needs to be done.
 */

import { UserState, Task, DocumentScan, ServicePreference } from '../types';

export interface LanternPDFData {
  // Personal Information (for official purposes)
  decedentName: string;
  dateOfBirth?: string;
  dateOfDeath?: string;
  placeOfDeath?: string;
  socialSecurityNumber?: string; // Last 4 digits only

  // Contact Information
  primaryContact: {
    name: string;
    relationship: string;
    phone: string;
    email: string;
  };

  // Funeral Service Preferences
  servicePreference: ServicePreference;
  serviceOutline?: string;

  // Key Milestones (What's been done, what's pending)
  completedTasks: string[];
  pendingTasks: string[];

  // Document Inventory (What documents are available)
  availableDocuments: string[];

  // Special Circumstances
  isVeteran: boolean;
  deathPronounced: boolean;
  deceasedLocation: 'HOME' | 'HOSPITAL' | 'OUT_OF_STATE' | 'UNKNOWN';
  userLocation: string;

  // Interstate Transport (if applicable)
  requiresInterstateTransport: boolean;
  transportOrigin?: string;
  transportDestination?: string;
}

/**
 * Generate the Lantern PDF content as formatted text
 * This can be printed, copied, or converted to PDF
 */
export function generateLanternContent(data: LanternPDFData): string {
  const today = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return `
╔═══════════════════════════════════════════════════════════════════════════════
                    THE LANTERN - LOGISTICAL LEDGER
                              ${today}
╚═══════════════════════════════════════════════════════════════════════════════

DECEDENT INFORMATION
─────────────────────────────────────────────────────────────────────────────
Name: ${data.decedentName.toUpperCase()}
${data.dateOfBirth ? `Date of Birth: ${data.dateOfBirth}` : ''}
${data.dateOfDeath ? `Date of Death: ${data.dateOfDeath}` : ''}
${data.placeOfDeath ? `Place of Death: ${data.placeOfDeath}` : ''}
${data.socialSecurityNumber ? `SSN (Last 4): ****-**-${data.socialSecurityNumber}` : ''}

PRIMARY CONTACT
─────────────────────────────────────────────────────────────────────────────
Name: ${data.primaryContact.name}
Relationship: ${data.primaryContact.relationship}
Phone: ${data.primaryContact.phone}
Email: ${data.primaryContact.email}

SERVICE PREFERENCES
─────────────────────────────────────────────────────────────────────────────
Service Type: ${data.servicePreference}
${data.serviceOutline ? `Service Notes: ${data.serviceOutline}` : ''}

CIRCUMSTANCES
─────────────────────────────────────────────────────────────────────────────
• Veteran Status: ${data.isVeteran ? 'Yes - Eligible for military honors' : 'No'}
• Death Pronounced: ${data.deathPronounced ? 'Yes - Officially pronounced' : 'No - Pending pronouncement'}
• Deceased Location: ${data.deceasedLocation}
• Current Location: ${data.userLocation}
• Interstate Transport: ${data.requiresInterstateTransport ? `Yes - From ${data.transportOrigin} to ${data.transportDestination}` : 'No'}

PROGRESS STATUS
─────────────────────────────────────────────────────────────────────────────

COMPLETED (${data.completedTasks.length}):
${data.completedTasks.map(t => `  ☑ ${t}`).join('\n')}

PENDING (${data.pendingTasks.length}):
${data.pendingTasks.map(t => `  ☐ ${t}`).join('\n')}

AVAILABLE DOCUMENTS
─────────────────────────────────────────────────────────────────────────────
${data.availableDocuments.map(d => `  • ${d}`).join('\n')}

╔═══════════════════════════════════════════════════════════════════════════════
This document is a formal summary of logistical information related to the
passing of ${data.decedentName}. It is intended for use by funeral directors,
transportation providers, and financial institutions.

For questions, please contact ${data.primaryContact.name} at ${data.primaryContact.phone}.

Generated by Lighthouse - Compassionate Estate Orchestration
╚═══════════════════════════════════════════════════════════════════════════════
`.trim();
}

/**
 * Extract Lantern data from UserState and Tasks
 */
export function extractLanternDataFromUserState(
  userState: UserState,
  tasks: Task[],
  documents: DocumentScan[]
): LanternPDFData {
  // Separate completed and pending tasks
  const completedTasks = tasks
    .filter(t => t.status === 'COMPLETED')
    .map(t => t.title);

  const pendingTasks = tasks
    .filter(t => t.status !== 'COMPLETED' && t.status !== 'DELEGATED')
    .sort((a, b) => {
      const priorityOrder = { URGENT: 0, HIGH: 1, NORMAL: 2, LOW: 3 };
      return (priorityOrder[a.priority] ?? 99) - (priorityOrder[b.priority] ?? 99);
    })
    .slice(0, 10) // Limit to top 10 pending tasks
    .map(t => t.title);

  // Extract document inventory
  const availableDocuments = documents.map(d => {
    const docName = d.name || `${d.type} Document`;
    const summary = d.summary ? ` - ${d.summary}` : '';
    return `${docName}${summary}`;
  });

  // Check if interstate transport is needed
  const requiresInterstateTransport = userState.deceasedLocation === 'OUT_OF_STATE';

  return {
    decedentName: userState.deceasedName || '[Name]',
    dateOfBirth: undefined, // Would be extracted from documents
    dateOfDeath: undefined,
    placeOfDeath: userState.deceasedLocation === 'HOSPITAL' ? 'Hospital/Facility' : undefined,
    socialSecurityNumber: undefined,
    primaryContact: {
      name: userState.name || '[Contact Name]',
      relationship: userState.relationshipToDeceased || '[Relationship]',
      phone: '[Phone Number]',
      email: '[Email Address]',
    },
    servicePreference: userState.servicePreference || 'SECULAR',
    serviceOutline: userState.serviceOutline,
    completedTasks,
    pendingTasks,
    availableDocuments,
    isVeteran: userState.isVeteran || false,
    deathPronounced: userState.deathPronounced || false,
    deceasedLocation: userState.deceasedLocation || 'UNKNOWN',
    userLocation: userState.userLocation || '[Location]',
    requiresInterstateTransport,
    transportOrigin: userState.userLocation,
    transportDestination: userState.deceasedLocation === 'OUT_OF_STATE' ? '[Destination]' : undefined,
  };
}

/**
 * Generate and trigger download of Lantern document
 */
export function downloadLanternPDF(data: LanternPDFData): void {
  const content = generateLanternContent(data);

  // Create a text file
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);

  // Create download link
  const link = document.createElement('a');
  link.href = url;
  link.download = `Lantern-${data.decedentName.replace(/\s+/g, '_')}-${Date.now()}.txt`;

  // Trigger download
  document.body.appendChild(link);
  link.click();

  // Cleanup
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Generate printable HTML version of Lantern
 */
export function generateLanternHTML(data: LanternPDFData): string {
  const content = generateLanternContent(data);

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>The Lantern - ${data.decedentName}</title>
  <style>
    body {
      font-family: 'Courier New', Courier, monospace;
      max-width: 800px;
      margin: 40px auto;
      padding: 20px;
      background: #fff;
      color: #000;
      line-height: 1.5;
    }
    pre {
      white-space: pre-wrap;
      font-family: 'Courier New', Courier, monospace;
    }
    @media print {
      body { margin: 0; padding: 20px; }
      .no-print { display: none; }
    }
    .print-btn {
      position: fixed;
      top: 20px;
      right: 20px;
      padding: 10px 20px;
      background: #000;
      color: #fff;
      border: none;
      border-radius: 5px;
      cursor: pointer;
      font-size: 14px;
    }
  </style>
</head>
<body>
  <button class="print-btn no-print" onclick="window.print()">Print / Save as PDF</button>
  <pre>${content.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</pre>
</body>
</html>
  `.trim();
}

/**
 * Open Lantern in new window for printing/saving as PDF
 */
export function openLanternForPrint(data: LanternPDFData): void {
  const html = generateLanternHTML(data);
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
  }
}

export default {
  generateLanternContent,
  extractLanternDataFromUserState,
  downloadLanternPDF,
  generateLanternHTML,
  openLanternForPrint,
};
